---
- name: Ensure Homebrew is installed
  ansible.builtin.shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /opt/homebrew/bin/brew
  when: ansible_facts['architecture'] == "arm64"

- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true
  tags: homebrew
